Fix WebSocket error
Removing .on() function because it is not a valid method and is causing
errors:
Uncaught TypeError: ws.on is not a function

The onerror event listener is already logging the error.

Signed-off-by: Yoshie Muranaka <yoshiemuranaka@gmail.com>
Change-Id: I6ccfa9a3a6beba93668b8c209b59560f4bf7b4bc