rsyslog: remove pin of specific version
The current pinned version no longer works with upstream. The following
error is logged building:

ERROR: rsyslog-8.1904.0-r0 do_configure: QA Issue: rsyslog: configure was passed unrecognised options: --enable-imfile-tests [unknown-configure-option]

Some investigation has not netted any solid reason on why this is needed
anymore.

(From meta-facebook rev: 51eee252deec4ba432fafd88d7e1c326cb09c5c9)

Signed-off-by: Andrew Geissler <geissonator@yahoo.com>
Change-Id: Ic53181fbf030614d7a01fb9205dfc4d44e99b6a9
Signed-off-by: Andrew Geissler <geissonator@yahoo.com>