phosphor-power: srcrev bump e6d54a1fd4..69f10ad0b5
Patrick Williams (1):
      exception: switch to public sdbus exception

Change-Id: I91523d65d7106514ae0a742c57045244f45563a5
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>