test/Makefile: Add sdbeventplus to LDFLAGS
Commit eb5d3f2fbcf584a28dc7aeaed050243ba0a038ea added a new
function that uses sdeventplus. This causes the test cases
to fail with:
undefined reference to `sdeventplus::Event::get_default().
Add the sdeventplus to LDFLAGS to fix it.

Tested: CI passes.

Change-Id: I6a5a79f15fc766be50ff78d9ee9d18e6380ef4d7
Signed-off-by: Adriana Kobylak <anoo@us.ibm.com>