openpower-pels: repository: fix use-after-free
    ERROR: AddressSanitizer: heap-use-after-free
    READ of size 4 at 0x60b0000007f0 thread T0
    #0 0x55b0e3e2740e in openpower::pels::Repository::remove(
        openpower::pels::Repository::LogID const&)
        ../extensions/openpower-pels/repository.cpp:228

This is caused by using an element out of a vector after it has
already been erased.  Modify function to avoid stale use.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I91a66a0fe45b82439cbe6c8c66463075b50aa953