astlpc: Remove unused rc variable
Detected with CFLAGS="-Wall -Werror":

astlpc.c: In function ‘mctp_astlpc_init_ops’:
astlpc.c:376:6: error: unused variable ‘rc’ [-Werror=unused-variable]
  376 |  int rc;
      |      ^~
cc1: all warnings being treated as errors

Signed-off-by: Andrew Jeffery <andrew@aj.id.au>
Change-Id: I4f7af2ec8b480caa08efff4c8ee7b0e0f1e4ac67