SdBusError: Fix missing move
Our move operator and constructor currently forgets that it needs to
also move the value of the system_error. It also needs to initialize the
error member since the move function will first free the current error.

Tested:
    Builds still work and existing tests pass.

Change-Id: I72fcd2d10eeedf6edf6f83c10ddaf15bb42c8b0d
Signed-off-by: William A. Kennington III <wak@google.com>