phosphor-objmgr: srcrev bump 21c6059531..e82b05840b
Patrick Williams (2):
      exception: switch from org.freedesktop to openbmc
      mapper-wait: handle switch to openbmc exceptions

(From meta-phosphor rev: 42112ddb3eae58696c26d44d64f1fd9561b62db2)

Change-Id: I1d7d2c1782755b20c29481c33c3a64f7c05d78c9
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>
Signed-off-by: Andrew Geissler <geissonator@yahoo.com>