Make clang-tidy pass
CI is failing on master due to clang-tidy failing for:

error: invalid case style for variable 'pkey_ctx'
[readability-identifier-naming,-warnings-as-errors]
            EVP_PKEY_CTX* pkey_ctx =
                          ^~~~~~~~
                          pkeyCtx

Change variable name to make clang-tidy happy.
This was introduced in 145bb764.

Tested: None. CI passing will validate clang-tidy passing.

Change-Id: Iedd8a40a871940066743ff8698dad53bfb0407c0
Signed-off-by: Gunnar Mills <gmills@us.ibm.com>