Logs: Move over to new Associations
Logging moved over to the new Associations interface here:
https://github.com/openbmc/phosphor-logging/commit/27d82814c3e79865221f599b98ce069c31c4d60a

Without this change was seeing:
TypeError: "r.data[h].associations is undefined"
    getLogs https://w81.aus.stglabs.ibm.com/app.bundle.js:41
    d https://w81.aus.stglabs.ibm.com/app.bundle.js:6
    d https://w81.aus.stglabs.ibm.com/app.bundle.js:6
    $digest https://w81.aus.stglabs.ibm.com/app.bundle.js:6
    $apply https://w81.aus.stglabs.ibm.com/app.bundle.js:6
    y https://w81.aus.stglabs.ibm.com/app.bundle.js:6
    C https://w81.aus.stglabs.ibm.com/app.bundle.js:6
    onload https://w81.aus.stglabs.ibm.com/app.bundle.js:6
Possibly unhandled rejection: {}

Added an hasOwnProperty before the foreach.

Tested: No longer see the error. See the "Related items:" on the
        event log panel.
Change-Id: I60be885feea72b1388b7cbf4c3a7b9df7dbb9a02
Signed-off-by: Gunnar Mills <gmills@us.ibm.com>