openpower-host-ipmi-flash: srcrev bump 61e18614a6..955103869d
Patrick Williams (1):
      exception: switch to public sdbus exception

Change-Id: Ie58edf935bfaf2a68e2ec16fc17dad6823b1f556
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>