Revert "Port obmc to python3.5"
Parse error with this change:
TypeError: iter() returned non-iterator of type 'PathTreeItemIterator'

This reverts commit f99783be6592130bbad2d0f69ada2b7ac61618f3.

Change-Id: Id2b7f4af5284d25d59e19905c7b873726b02f700
Signed-off-by: Brad Bishop <bradleyb@fuzziesquirrel.com>