exception: switch from org.freedesktop to openbmc
sd-bus makes it nearly impossible to differentiate between
`org.freedesktop.DBus.Error` types caused by the sd-bus library or
returned by an application.  Therefore, we should migrate to having no
error types of `org.freedesktop.DBus.*`, in order to allow clients to
differentiate.  There are no cases currently where code is explicitly
looking for `FileNotFound`, so there should not be any dependencies on
this change.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I414b8a19556a8608561fee912733e04bea1a2b3e