openpower-pnor-code-mgmt: srcrev bump 5dc5d6cc67..7b5685d105
Adriana Kobylak (1):
      Update MAINTAINERS, add OWNERS

Patrick Williams (1):
      exception: switch to public sdbus exception

Change-Id: If9daffb053e7392d63d6ff01062e20a7fd756702
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>