console-server: fix initialiser
When using clang (3.8, and 3.4), the initaliser for struct option:

console-server.c:471:6: error: missing field 'has_arg' initializer
  [-Werror,-Wmissing-field-initializers]
        { 0 },

Shut the compiler up by using four zeros, which is what the libc manual
suggests:

 "Terminate the array with an element containing all zeros."

Signed-off-by: Joel Stanley <joel@jms.id.au>