lib: skip Journal in redfish enumerate
Symptom:
"Verify Redfish Unresponsive URL paths" test item got failed.
ValueError: The HTTP status code was not valid:
status:                                           400
valid_status_codes:
  [0]:                                            200
  [1]:                                            404
  [2]:                                            405
  [3]:                                            500

Root cause:
When doing Redfish Enumerate Request into /redfish/v1/Managers/bmc/LogServices/Journal,
The response status code return 400 that is not in valid_status_codes list.

Seems journal entries will be overwrited when entries full.
Thus, when enumerating the overwrited log entries will got failed.
Currently, "OverWritePolicy" is "WrapsWhenFull" in LogService.json schema.

Solution:
Skip Journal in redfish enumerate request.

Tested:
Run all robot test cases.

Signed-off-by: Tim Lee <timlee660101@gmail.com>
Change-Id: Iad7c2bf83f2645fcbf191400267f2a2f68e31806