Revert "libpldm: Remove states.h file"
This reverts commit b011526d45c7866dd391d1358a6bdc04e28613ea.

CI of other repos that depend on libpldm are failing. For eg https://jenkins.openbmc.org/job/ci-repository/1676/console.

FAILED: libpldmresponder/1b80d8d@@pldmresponder@sha/platform.cpp.o 
c++ -Ilibpldmresponder/1b80d8d@@pldmresponder@sha -Ilibpldmresponder -I../libpldmresponder -Ilibpldm -I../libpldm -I. -I.. -I../oem/ibm -I../libpldm/requester -I/usr/local/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -Werror -std=c++17 -g -Wno-psabi -DOEM_IBM -fPIC -MD -MQ 'libpldmresponder/1b80d8d@@pldmresponder@sha/platform.cpp.o' -MF 'libpldmresponder/1b80d8d@@pldmresponder@sha/platform.cpp.o.d' -o 'libpldmresponder/1b80d8d@@pldmresponder@sha/platform.cpp.o' -c ../libpldmresponder/platform.cpp
In file included from ../libpldmresponder/platform.cpp:2:
../libpldmresponder/platform.hpp:6:10: fatal error: libpldm/states.h: No such file or directory
    6 | #include "libpldm/states.h"
      |          ^~~~~~~~~~~~~~~~~~

Change-Id: I38c1d2f0c881945167e0100702a2dd45321c212f