i2c: Initialize variable ret
The varialbe `ret` in some functions is not initialized and cause the
build warning and treated as error:

    error: 'ret' may be used uninitialized in this function
    [-Werror=maybe-uninitialized]

Fixes openbmc/phosphor-power#3.

Signed-off-by: Lei YU <yulei.sh@bytedance.com>
Change-Id: Ica6b1af434736f6fd96a1bbb9e511bf1c8fb1d7a