meta-phosphor: phosphor-ipmi-flash: Update recipe to use meson
The new meson now forced only one type of LPC or P2A to be enabled.
The build will fail if both LPC and P2A are enabled.

Out of the given type, only the last package enabled will be used.

Added PACKAGECONFIG conflict feature.

Tested
```
NOTE: Reconnecting to bitbake server...
Loading cache: 100% |###################################################################################################################################################################################################| Time: 0:00:01
Loaded 3939 entries from dependency cache.
ERROR: /workspace/gBMC/buildspace/gbmc/meta-phosphor/recipes-phosphor/ipmi/phosphor-ipmi-flash_git.bb: phosphor-ipmi-flash: PACKAGECONFIG[nuvoton-lpc] Conflict package config 'nuvoton-p2a-mbox' set in PACKAGECONFIG.| ETA:  --:--:--
ERROR: Failed to parse recipe: /workspace/gBMC/buildspace/gbmc/meta-phosphor/recipes-phosphor/ipmi/phosphor-ipmi-flash_git.bb
```

Change-Id: I6ad9317cb5c35aa266ff67eb3b22e9f5f17f359b
Signed-off-by: Willy Tu <wltu@google.com>