exception: Remove unused sdbus_impl declaration
Change 9ff25f7365d4d590fcb5349328a46a8cd2093f34 exposed the sdbus_impl
globally from the sdbus.hpp file. Remove this leftover declaration
since it is no longer needed.

Tested:
    Built and run through the unit test suite.

Change-Id: I39484959978b07dd27aa3b3f3c0f046c5aa9b515
Signed-off-by: William A. Kennington III <wak@google.com>