cpusensor: Move kernel includes to the end
When updating to the newest kernel it appears config.h
got the namespace keyword checked in which is making
C++ throw a fit. Moving it to the end seems to get rid
of the issue.

arm-openbmc-linux-gnueabi/bits/c++config.h:253:10: error: expected unqualified-id before 'namespace'
|    inline namespace __cxx11 __attribute__((__abi_tag__ ("cxx11"))) { }

Change-Id: I896c63e56ea3e9d4fbdeb133bb8fa913db19f7b4
Signed-off-by: James Feist <james.feist@linux.intel.com>