autobump: set topic per new gerrit
Gerrit was upgraded and appears to require the topic now be set via the
topic parameter.

Code as-is started giving this error when running script:

remote: Processing changes: refs: 1, done
To ssh://openbmc.gerrit/openbmc/meta-intel
 ! [remote rejected] HEAD -> refs/for/master/autobump (branch master/autobump not found)
error: failed to push some refs to 'ssh://openbmc.gerrit/openbmc/meta-intel'

Tested:
- Verified script properly updated gerrit with autobump topic

Change-Id: I4a68124c324392c3efcf7683b81ac5152aa8a3d9
Signed-off-by: Andrew Geissler <geissonator@yahoo.com>