ipmi-fru-parser: srcrev bump 904a218483..5f5e3840f7
Patrick Williams (1):
      exception: switch to public sdbus exception

Change-Id: I25bc09edd7dd336537afdb91f84c85c627e808e5
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>