phosphor-certificate-manager: srcrev bump 6dd1c2ad86..ca12811702
Patrick Williams (2):
      cleanup sdbus CAMELCASE define
      exception: switch to public sdbus exception

Change-Id: I50ce5f897768dc068876bc45fe1c5730945a6d9e
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>