Fix build with rest option disabled
When the rest option is disabled the build fails with the following
error:
ERROR: Unknown variable "tinyxml".

This change creates a bmcweb_dependencies variable that is updated
as new dependencies are defined.  This allows the tinyxml
dependency to be added as part of the 'rest' option so it isn't in
the dependency list when the option is disabled.

Change-Id: Id392dd068902643cf90ec135733c31bf265bf75f
Signed-off-by: Jason M. Bills <jason.m.bills@linux.intel.com>