openpower-host-ipmi-oem: srcrev bump 98af91d62e..7bb95c3e23
Patrick Williams (1):
      exception: switch to public sdbus exception

Change-Id: I0148d2cba49f23cfcf342034c30f7e60853f1f9d
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>