asio: object_server: remove unused variable
Reported by clang:

    ../subprojects/sdbusplus/include/sdbusplus/asio/object_server.hpp:245:33: error: unused parameter 'm' [-Werror,-Wunused-parameter]
            callFunction(message_t& m, InputTupleType& inputArgs)

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I1a53b0aef444d80f1b1f4af6192d59ccd0381aaf