elog-gen: allow inherits from errors without meta
Previously, elog-gen only support inherits from errors that have meta,
and if we inherit from an error without meta, e.g.
Common.InternalFailure, we get build error like:

    KeyError: 'xyz.openbmc_project.Common.InternalFailure'

This commit makes elog-gen to allow such case, so it is possible to
allow a base error without meta, and inheriting error with additional
error, e.g.

    # In Common:
    - name: NotAllowed  ## No meta

    # In Time:
    - name: NotAllowed
      inherits:
        - xyz.openbmc_project.Common.NotAllowed
      meta:
        - str: "OWNER=%s"
          type: string
        - str: "SYNC_METHOD=%s"
          type: string

Note: the "inherit" here does not mean the the error inherits from
base errors in c++ class, it just makes error "logically" inherits base
errors. And in future commits we could make it "really" inherits base
errors in c++ level.

Tested: Verify phosphor-logging builds correctly with above example
        error interfaces, and service is able to use such errors with
        elog.

Change-Id: I8dccd7112881e3eb77a8f6ec62a532062348d2ef
Signed-off-by: Lei YU <mine260309@gmail.com>