nemora-postd: fix compile fail
host_manager.hpp is missing header for `std::thread`.

```
In file included from ../subprojects/nemora-postd/src/nemora.hpp:17,
                 from ../subprojects/nemora-postd/src/nemora.cpp:15:
../subprojects/nemora-postd/src/host_manager.hpp:76:26: error: ‘thread’ is not a member of ‘std’
   76 |     std::unique_ptr<std::thread> post_poller_;
```

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Icda54302f7770e5760dfa3c509c7086e47af75f9