utils: Resolve warnings of unused write() result
For example:

```
utils/mctp-pipe.c:19:9: error: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
   19 |         write(STDOUT_FILENO, msg, len);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Signed-off-by: Andrew Jeffery <andrew@aj.id.au>
Change-Id: I57041dc85b551f9bb694638642b677b737be21eb