phosphor-watchdog: srcrev bump 9ef0d0fbac..15c5bd1b60
Patrick Williams (1):
      exception: switch to public sdbus exception

Change-Id: I3fcbb54bb70185af9c3c44c93ce0d38a42f4e36d
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>