phosphor-psu-code-mgmt: srcrev bump 7905f587ac..6d62ceb307
Patrick Williams (1):
      exception: switch to public sdbus exception

Change-Id: Ifae7b947c9a0667eea73657a04ada130e21bb873
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>