Cleanup of code to pass CI, clang-tidy-13
With the move to clang-tidy-13 entity-manager wasn't passing CI.
    src/Utils.cpp:76:34: error: statement should be inside braces

Tested: After code update entity-manager is now passing CI with
clang-tidy-13.

Signed-off-by: Bruce Mitchell <bruce.mitchell@linux.vnet.ibm.com>
Change-Id: I54e9e7b0dc825dc860338df47bad5a5952d80d02